aws_region         = "ap-southeast-1"
project_name       = "tf-cicd"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
instance_type      = "t2.micro"
ami_id             = "ami-0497a974f8d5dcef8"
alert_email        = "haziqhakimiyes@gmail.com"
